include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "solver")
set(CPACK_PACKAGE_VENDOR "justtavinay-coder")
set(CPACK_PACKAGE_CONTACT "234632310+justtavinay-coder@users.noreply.github.com")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${PROJECT_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "C++ quadratic equation solver")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "solver")

# WiX (MSI) требует лицензию с расширением .txt/.rtf, поэтому на Windows
# используем текстовую копию лицензии.
if(WIN32)
  set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.txt)
else()
  set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
endif()
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

# Набор генераторов по умолчанию выбирается по платформе.
# Можно переопределить через -DCPACK_GENERATOR="...".
if(NOT CPACK_GENERATOR)
  if(WIN32)
    set(CPACK_GENERATOR "ZIP;WIX")
  elseif(APPLE)
    set(CPACK_GENERATOR "TGZ;DragNDrop")
  else()
    set(CPACK_GENERATOR "TGZ;ZIP;DEB;RPM")
  endif()
endif()

set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES
  /.git/
  /_build/
  /artifacts/
)

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")

# DEB (Linux)
set(CPACK_DEBIAN_PACKAGE_NAME "solver")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER ${CPACK_PACKAGE_CONTACT})
set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

# RPM (Linux)
set(CPACK_RPM_PACKAGE_NAME "solver")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Applications/Engineering")
set(CPACK_RPM_CHANGELOG_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md)
set(CPACK_RPM_PACKAGE_RELEASE 1)

# WIX (Windows / MSI)
set(CPACK_WIX_UPGRADE_GUID "6B8A2C44-9E3D-4F1A-B2C7-1D5E6F7A8B90")

# DragNDrop (macOS / DMG) использует значения по умолчанию.

install(FILES
  ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION
  ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md
  DESTINATION share/doc/solver
)

include(CPack)
